---
abstract: 'Auth::RBAC Permissions via DBIx::Class'
author:
  - 'Jason Clifford <jason@ukfsn.org>'
build_requires:
  DBIx::Class::Core: 0
  DBIx::Class::Schema: 0
  File::Temp: 0
  SQL::Translator: 0.11006
  Test::More: 0
  ok: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dancer-Plugin-Auth-RBAC-Permissions-DBIC
no_index:
  directory:
    - t
    - inc
requires:
  Dancer::Plugin::Auth::RBAC::Credentials::DBIC: 0
  Dancer::Plugin::Auth::RBAC::Permissions: 0
  Dancer::Plugin::DBIC: 0.15
  parent: 0
version: 0.002
